# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Inicio
    url: /#top
    weight: 10
  - name: Nosotros
    url: /#features
    weight: 20
  - name: Lotes Disponibles
    url: /#solutions
    weight: 30
  - name: Contacto
    url: /contacto
    weight: 40
    hasChildren: true
  - parent: Publicaciones
    name: Blog
    url: blog/
